name: selectable
description: A Flutter widget that enables text selection over all the text widgets it contains.
version: 0.2.6
repository: https://github.com/ronjb/selectable

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  characters: ^1.2.1
  collection: ^1.16.0
  equatable: ^2.0.5
  float_column: ^1.3.0
  flutter:
    sdk: flutter
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_lints_plus: ^2.0.1
  flutter_test:
    sdk: flutter
