name: selectable
description: A Flutter widget that enables text selection over all the text widgets it contains.
version: 0.3.0
repository: https://github.com/ronjb/selectable

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  characters: ^1.2.0
  collection: ^1.16.0
  equatable: ^2.0.5
  float_column: ^2.0.0
  flutter:
    sdk: flutter
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_lints_plus: ^2.0.1
  flutter_test:
    sdk: flutter
